<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class TelegramType extends AbstractType
{
//    public function buildForm(FormBuilderInterface $builder, array $options)
//    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
//    }
}
